In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [ ]:
df=pd.read_csv('/content/house_prices.csv')

In [ ]:
df.head()

   sqft_living  bedrooms  bathrooms  ...  dist_to_city_km  quality_score   price
0          959         4        2.0  ...            13.97              6  256153
1         3173         4        2.6  ...             1.40              4  602494
2         2017         1        1.9  ...             0.24              9  403973
3          818         5        3.7  ...            13.07              3  208514
4         2036         3        2.3  ...             1.90              5  396980

[5 rows x 8 columns]

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.describe()

       sqft_living     bedrooms  ...  quality_score         price
count  1000.000000  1000.000000  ...    1000.000000  1.000000e+03
mean   1872.225000     3.368000  ...       6.581000  4.081768e+05
std     721.658094     1.189955  ...       2.240638  1.518990e+05
min     450.000000     1.000000  ...       3.000000  8.956100e+04
25%    1362.000000     3.000000  ...       5.000000  3.257180e+05
50%    1873.500000     3.000000  ...       7.000000  4.020970e+05
75%    2358.000000     4.000000  ...       9.000000  4.792382e+05
max    3927.000000     6.000000  ...      10.000000  2.558280e+06

[8 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sqft_living      1000 non-null   int64
 1   bedrooms         1000 non-null   int64
 2   bathrooms        988 non-null    float64
 3   floors           1000 non-null   float64
 4   house_age        1000 non-null   int64
 5   dist_to_city_km  1000 non-null   float64
 6   quality_score    1000 non-null   int64
 7   price            1000 non-null   int64
dtypes: float64(3), int64(5)
memory usage: 62.6 KB

In [ ]:
df.isnull().sum()

sqft_living         0
bedrooms            0
bathrooms          12
floors              0
house_age           0
dist_to_city_km     0
quality_score       0
price               0
dtype: int64

In [ ]:
df['bathrooms']=df['bathrooms'].fillna(df['bathrooms'].median())
df.isnull().sum()

sqft_living        0
bedrooms           0
bathrooms          0
floors             0
house_age          0
dist_to_city_km    0
quality_score      0
price              0
dtype: int64

In [ ]:
from re import I
q1=df['price'].quantile(0.25)
q3=df['price'].quantile(0.75)
iqr=q3-q1
upper=q3+3*iqr
df=df[df['price']<=upper]
df.shape

(997, 8)

In [ ]:
x=df.drop(columns='price')
y=df['price']

In [ ]:
print(x)

     sqft_living  bedrooms  ...  dist_to_city_km  quality_score
0            959         4  ...            13.97              6
1           3173         4  ...             1.40              4
2           2017         1  ...             0.24              9
3            818         5  ...            13.07              3
4           2036         3  ...             1.90              5
..           ...       ...  ...              ...            ...
995         2530         2  ...             6.32              3
996         1159         3  ...             1.00              5
997         2530         3  ...             3.36              9
998          785         1  ...             0.77              5
999         3076         3  ...             5.67              6

[997 rows x 7 columns]

In [ ]:
print(y)

0      256153
1      602494
2      403973
3      208514
4      396980
        ...
995    442706
996    290977
997    512494
998    242206
999    574995
Name: price, Length: 997, dtype: int64

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(x)
x_std=scaler.transform(x)

In [ ]:
print(x_std)

[[-1.26516212  0.5313711  -0.55215823 ... -0.50272299  0.77894603
  -0.26273531]
 [ 1.80119768  0.5313711   0.07436122 ... -0.55543805 -0.86580809
  -1.15675274]
 [ 0.20015345 -1.99137647 -0.65657814 ...  2.71289585 -1.01759129
   1.07829083]
 ...
 [ 0.91065145 -0.30954475 -0.44773833 ...  0.92058371 -0.60934683
   1.07829083]
 [-1.50614974 -1.99137647 -1.59635732 ... -0.81901336 -0.94824207
  -0.70974402]
 [ 1.666854   -0.30954475 -0.34331842 ... -0.02828742 -0.30708891
  -0.26273531]]

In [ ]:
x=x_std

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(997, 7) (797, 7) (200, 7)

In [ ]:
cf=RandomForestRegressor(n_estimators=200,max_depth=10,random_state=2)

In [ ]:
cf.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=2)

In [ ]:
x_train_pred=cf.predict(x_train)

In [ ]:
x_train_r=r2_score(y_train,x_train_pred)

In [ ]:
print(x_train_r)

0.9914272926864008

In [ ]:
x_test_pred=cf.predict(x_test)
x_test_r=r2_score(y_test,x_test_pred)
print(x_test_r)

0.9438451796541517

In [ ]:
data=[2150,3,2.0,2.0,8,5.4,7]
print(data)

[2150, 3, 2.0, 2.0, 8, 5.4, 7]

In [ ]:
data_np=np.asarray(data)
print(data_np)

[2.15e+03 3.00e+00 2.00e+00 2.00e+00 8.00e+00 5.40e+00 7.00e+00]

In [ ]:
data_reshaped=data_np.reshape(1,-1)

In [ ]:
input_std=scaler.transform(data_reshaped)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
print(input_std)

[[ 0.38435664 -0.30954475 -0.55215823  0.61887141 -0.60815311 -0.34241776
   0.1842734 ]]

In [ ]:
pred=cf.predict(input_std)
print(pred)

[455583.82255849]