In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv('/content/winequality.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1607 entries, 0 to 1606
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1607 non-null   float64
 1   volatile acidity      1607 non-null   float64
 2   citric acid           1607 non-null   float64
 3   residual sugar        1607 non-null   float64
 4   chlorides             1595 non-null   float64
 5   free sulfur dioxide   1607 non-null   float64
 6   total sulfur dioxide  1607 non-null   float64
 7   density               1607 non-null   float64
 8   pH                    1592 non-null   float64
 9   sulphates             1588 non-null   float64
 10  alcohol               1607 non-null   float64
 11  quality               1607 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.8 KB

In [4]:
df.head()

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0           8.94             0.507         0.29  ...       0.62     9.89        5
1           8.42             0.681         0.19  ...       1.10    11.77        6
2           9.65             0.362         0.35  ...       0.68     9.69        5
3           5.63             0.278         0.50  ...       0.72    10.90        6
4           6.49             0.474         0.59  ...       0.67    11.01        5

[5 rows x 12 columns]

In [6]:
df.describe()

       fixed acidity  volatile acidity  ...      alcohol      quality
count    1607.000000       1607.000000  ...  1607.000000  1607.000000
mean        8.291077          0.525606  ...    10.438419     5.589297
std         1.682200          0.176942  ...     1.072897     0.716700
min         4.600000          0.120000  ...     8.400000     4.000000
25%         7.150000          0.407000  ...     9.660000     5.000000
50%         8.290000          0.521000  ...    10.410000     6.000000
75%         9.430000          0.639000  ...    11.170000     6.000000
max        15.360000          1.075000  ...    14.340000     8.000000

[8 rows x 12 columns]

In [7]:
df.shape

(1607, 12)

In [8]:
df.isnull().sum()

fixed acidity            0
volatile acidity         0
citric acid              0
residual sugar           0
chlorides               12
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                      15
sulphates               19
alcohol                  0
quality                  0
dtype: int64

In [9]:
df['chlorides']=df['chlorides'].fillna(df['chlorides'].median())

In [12]:
df['pH']=df['pH'].fillna(df['pH'].median())

In [15]:
df['sulphates']=df['sulphates'].fillna(df['sulphates'].median())
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [18]:
import re as I
q1 = df['quality'].quantile(0.25)
q3 = df['quality'].quantile(0.75)
iqr = q3 - q1

upper = q3 + 3 * iqr
lower = q1 - 3 * iqr

df = df[(df['quality'] >= lower) & (df['quality'] <= upper)]
df.shape

(1607, 12)

In [17]:
x=df.drop(columns='quality')
y=df['quality']

In [21]:
scaler=StandardScaler()

In [26]:
scaler.fit(x)
x_std=scaler.transform(x)

In [27]:
x=x_std

In [75]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [76]:

print(x.shape,x_train.shape,x_test.shape)

(1607, 11) (1285, 11) (322, 11)

In [113]:
cf=RandomForestRegressor(n_estimators=100,max_depth=4,random_state=42)

In [114]:
cf.fit(x_train,y_train)

RandomForestRegressor(max_depth=4, random_state=42)

In [115]:
x_train_pred=cf.predict(x_train)

In [116]:
x_train_r=r2_score(y_train,x_train_pred)

In [117]:
print(x_train_r)

0.3795028575763697

In [118]:
x_test_pred=cf.predict(x_test)
x_test_r=r2_score(y_test,x_test_pred)
print(x_test_r)

0.34852076610917493

In [130]:
data=[0.9978,3,1.9,3,8,5.4,7,11,3.51,0.0,4.2,]
print(data)

[0.9978, 3, 1.9, 3, 8, 5.4, 7, 11, 3.51, 0.0, 4.2]

In [131]:
data_np=np.asarray(data)
print(data_np)

[ 0.9978  3.      1.9     3.      8.      5.4     7.     11.      3.51
  0.      4.2   ]

In [132]:
data_reshap=data_np.reshape(1,-1)

In [133]:
input_std=scaler.transform(data_reshap)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [135]:
print(input_std)

[[-4.33690748e+00  1.39885742e+01  9.03754995e+00  1.66158827e-01
   1.78020945e+02 -1.15558848e+00 -1.93138571e+00  5.48617618e+03
   1.26811720e+00 -4.06177999e+00 -5.81636764e+00]]

In [136]:
pred=cf.predict(input_std)
print(pred)

[4.60092666]