In [32]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [33]:
df=pd.read_csv('/content/heart_disease.csv')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       500 non-null    int64
 1   sex       500 non-null    object
 2   cp        500 non-null    int64
 3   trestbps  495 non-null    float64
 4   chol      490 non-null    float64
 5   fbs       500 non-null    int64
 6   restecg   500 non-null    int64
 7   thalach   493 non-null    float64
 8   exang     500 non-null    int64
 9   oldpeak   500 non-null    float64
 10  slope     500 non-null    int64
 11  ca        500 non-null    int64
 12  thal      500 non-null    int64
 13  target    500 non-null    int64
dtypes: float64(4), int64(9), object(1)
memory usage: 54.8+ KB

In [35]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,42,male,0,94.0,310.5,1,0,179.4,0,1.85,2,2,1,0
1,31,Female,2,116.9,248.6,0,0,153.5,1,1.99,1,0,2,0
2,64,Male,3,133.3,260.9,0,1,136.8,0,0.07,2,0,2,1
3,58,male,0,124.4,229.7,0,0,173.9,0,1.68,1,2,1,0
4,45,Female,1,148.8,258.7,0,0,186.3,1,1.16,1,2,2,0

In [36]:
df.describe()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,500.00000,500.000000,495.000000,490.000000,500.000000,500.000000,493.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,53.52800,0.938000,131.196566,243.353061,0.156000,0.510000,148.295538,0.326000,1.013400,1.422000,0.750000,2.326000,0.404000
std,9.36058,1.008062,16.790346,51.225905,0.363219,0.512274,22.668989,0.469217,1.008851,0.607168,1.055333,0.579997,0.491189
min,29.00000,0.000000,94.000000,126.000000,0.000000,0.000000,85.700000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,47.00000,0.000000,119.250000,209.950000,0.000000,0.000000,131.800000,0.000000,0.230000,1.000000,0.000000,2.000000,0.000000
50%,54.00000,1.000000,131.200000,244.300000,0.000000,1.000000,148.300000,0.000000,0.685000,1.000000,0.000000,2.000000,0.000000
75%,60.00000,2.000000,142.250000,277.200000,0.000000,1.000000,163.100000,1.000000,1.422500,2.000000,1.000000,3.000000,1.000000
max,77.00000,3.000000,183.200000,376.600000,1.000000,2.000000,202.000000,1.000000,5.650000,2.000000,4.000000,3.000000,1.000000

In [37]:
df.shape

(500, 14)

In [57]:
print(df.isnull().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [58]:
df['trestbps'] = df['trestbps'].fillna(df['trestbps'].median())

df['chol'] = df['chol'].fillna(df['chol'].median())

df['thalach'] = df['thalach'].fillna(df['thalach'].median())

In [59]:
le = LabelEncoder()

df['sex'] = le.fit_transform(df['sex'])

In [60]:
df['target'].value_counts()

target
0    298
1    202
Name: count, dtype: int64

In [61]:
df.groupby('target').mean()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
target,,,,,,,,,,,,,
0,52.657718,1.010067,0.822148,132.079866,241.542282,0.130872,0.503356,154.276510,0.315436,0.920973,1.439597,0.503356,2.332215
1,54.811881,0.985149,1.108911,129.893564,246.071287,0.193069,0.519802,139.472277,0.341584,1.149752,1.396040,1.113861,2.316832

In [62]:
x=df.drop(columns='target',axis=1)
y=df['target']

In [63]:
print(x)

     age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     42    3   0      94.0  310.5    1        0    179.4      0     1.85
1     31    0   2     116.9  248.6    0        0    153.5      1     1.99
2     64    1   3     133.3  260.9    0        1    136.8      0     0.07
3     58    3   0     124.4  229.7    0        0    173.9      0     1.68
4     45    0   1     148.8  258.7    0        0    186.3      1     1.16
..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...
495   49    3   2     126.1  274.8    0        0    171.8      1     1.49
496   53    2   2     136.5  251.9    0        1    171.4      1     0.12
497   58    1   2     168.1  236.4    0        0    156.4      1     0.21
498   59    3   0     134.6  243.6    0        0    153.1      0     2.28
499   67    0   0     183.2  266.9    0        0    197.0      0     2.46

     slope  ca  thal
0        2   2     1
1        1   0     2
2        2   0     2
3        1   2     1
4        1   2     2
..     ...  ..   ...
495      1   0     3
496      2   0     3
497      2   1     2
498      1   1     2
499      1   0     2

[500 rows x 13 columns]

In [64]:
print(y)

0      0
1      0
2      1
3      0
4      0
      ..
495    0
496    0
497    0
498    1
499    0
Name: target, Length: 500, dtype: int64

In [65]:
scaler=StandardScaler()

In [66]:
scaler.fit(x)
x_std=scaler.transform(x)

In [67]:

x=x_std

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [69]:
print(x.shape,x_train.shape,x_test.shape)

(500, 13) (400, 13) (100, 13)

In [70]:
cf=svm.SVC(kernel="linear")

In [71]:
cf.fit(x_train,y_train)

SVC(kernel='linear')

In [72]:
x_train_pred=cf.predict(x_train)

In [73]:
x_train_acc=accuracy_score(x_train_pred,y_train)

In [74]:
print(x_train_acc)

0.74

In [75]:
x_test_pred=cf.predict(x_test)

In [76]:
x_test_acc=accuracy_score(x_test_pred,y_test)

In [77]:
print(x_test_acc)

0.74

In [84]:
input_data = [52,1,2,120,240,0,1,150,0,1.2,1,0,2]

In [85]:
data=np.asarray(input_data)
print(data)

[ 52.    1.    2.  120.  240.    0.    1.  150.    0.    1.2   1.    0.
   2. ]

In [86]:
data_reshaped=data.reshape(1,-1)

In [87]:
input_std=scaler.transform(data_reshaped)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [88]:
print(input_std)

[[-0.16340123  0.          1.05456204 -0.67088495 -0.0665621  -0.42992339
   0.95747696  0.07579522 -0.69547072  0.18514817 -0.69572581 -0.71138799
  -0.56263456]]

In [89]:
pred=cf.predict(input_std)
print(pred)
if(pred[0]==0):
  print("No heartdisease")
else:
  print("heartdisease")

[0]
No heartdisease

In [90]:
pred=cf.predict(input_std)
print(pred)

[0]

In [91]:
print(x.shape)

(500, 13)